ietf-wg-dance/draft-dance-architecture

draft-wilson-dance-architecture.md
Add privacy considerations as raised on the mailing list.
=> Add privacy considerations

draft-dance-architecture.md, draft-ietf-dance-architecture.md
added mcr as co-author.
please also give me permissions to ietf-wg-dance!
=> get draft renamed and tag for -00

draft-johansson-dance-implementation-profile-guide.md
Copied the arch draft file and cleaned up. Left terminology for now.
=> Adding a very thin file for implementation-profile-guide

draft-ietf-dance-architecture.md
=> SC section on change of ownership

draft-ietf-dance-architecture.md
=> add TTL discussion to Availability section

draft-ietf-dance-architecture.md
Work in progress to clean up the architecture document.
=> Adding issue id's in text, small clean up

draft-ietf-dance-architecture.md
=> added description of benefits of using DNS for SSH client keys

draft-ietf-dance-architecture.md
=> text about EAP-TLS use of client side certificates

draft-ietf-dance-architecture.md
Simplified LoRaWAN Use Case version
=> Added a simplified version of LoRaWAN USe-Case

draft-ietf-dance-architecture.md
=> Dancing with DNS

draft-ietf-dance-architecture.md
=> Fix spelling issue

draft-ietf-dance-architecture.md
=> added STARTTLS use case, close #8

draft-ietf-dance-architecture.md
As pointed out in SECDIR review
=> Add text on DDos for TLS servers

draft-ietf-dance-architecture.md
=> Sorting out markdown heading levels

draft-ietf-dance-architecture.md
=> Move reference to SIP Dane draft into sentence

draft-ietf-dance-architecture.md
=> Don't use "BCP" when there is not published official BCP

draft-ietf-dance-architecture.md
=> Add reference to 5280

draft-ietf-dance-architecture.md
=> provide a reference to Slowlaris attack

draft-ietf-dance-architecture.md
=> Expand text on TTL usage

draft-ietf-dance-architecture.md
closes #52 
closes #61 
- Adds example headers on all examples
- Add initial text on requirements on "how to dance"
=> Add requirements on "how to dance"

.github/workflows/archive.yml, .github/workflows/ghpages.yml, .github/workflows/publish.yml
=> Upgrade upload-artifact to v4

draft-ietf-dance-architecture.md
=> Add reference to new RFC for internationalised email addresses

draft-ietf-dance-architecture.md
=> Remove "TBD" as these are documented in the other draft

draft-ietf-dance-architecture.md
=> Remove all the "circumstances" and provide a bullet list of examples.

draft-ietf-dance-architecture.md
close #43
not sure where to reference this paper.
=> added reference to Sandoche paper; but not sure where to reference it
